mongodb-js/compass-import-export

- src/components/export-modal/export-modal.jsx
- src/components/query-viewer/query-viewer.jsx
- src/utils/get-shell-js.js
- src/utils/get-shell-js.spec.js
Instead of the query viewer containing only the query predicate:
```javascript
{}
```
We now include a shell snippet that includes skip/limit/project set in the query bar, in addition, to the predicate:
```javascript
db.pets.find(
{name:'Arlo'},
{name:1}
).limit(100).skip(0)
```
> COMPASS-3825: Show skip/limit/project in query view on export

- src/components/import-modal/import-modal.jsx
- src/components/progress-bar/progress-bar.jsx
- src/modules/import.js
- src/utils/collection-stream.js
- src/utils/import-size-guesstimator.js
- src/utils/import-size-guesstimator.spec.js
- src/utils/parsers.js
- src/utils/remove-empty-fields.js
This PR is refactoring to minimize logic within `startImport()` and allow fine-grained testing of stream-based components now that we're confident they'll stick around.
> Simplify start import

- .travis.yml
This PR updates the travis config so that functional tests now tests against latest stable server version (currently 4.2.x) instead of hardcoded `3.4.x` (😬) .
> chore: update travis server version

- .travis.yml
- package.json
This PR configures `compass-import-export` to deploy [its storybook](https://github.com/mongodb-js/compass-import-export/tree/master/examples) to GitHub pages after the master branch successfully builds and passes tests. This configuration follows the same model as [compass-aggregations](https://mongodb-js.github.io/compass-aggregations).
> feat: Travis deploys storybook to ghpages on successful builds

- src/components/import-modal/import-modal.jsx
- src/components/progress-bar/progress-bar.jsx
- src/components/progress-bar/progress-bar.less
Configures import buttons based on current import state. 
- `Cancel` and `Import` are present when file is not yet imported
- `Close` and `Import` are present when file import was stopped
- `...Importing` is present as disabled when file is in the middle of import
- `Stop` anchor link is present along with a progress bar
- `Done` button is present after import successfully completed
Result looks like this:
> COMPASS-3949: buttons based on current import state

- src/components/export-field/export-field.less
- src/components/export-select-fields/export-select-fields.jsx
- src/components/export-select-fields/export-select-fields.less
Adds a `+ ADD FIELD` button with an input field in export-fields modal. 
`+ ADD FIELD` button scrolls over to the bottom of the table and focuses on the input field to be edited. The field is only saved on `enter`, which is indicated by the text on the side of the table. When the input field is submitted, `fields` props are updated and the component is refreshed. That particular field is saved even after the user goes to `OUTPUT` and comes back to `FIELDS`. 
Currently once I hit enter to save the currently edited field, I am not able to prevent the modal from scrolling up a bit. This happens because the element is rerendering, so I understand that the state just changed and the focus was lost. Anyone have an idea as to how to get the focus back to the previous state, aka the input field …
> COMPASS-3961: allow adding missing fields

- src/components/query-viewer/query-viewer.jsx
- src/components/query-viewer/query-viewer.less
- src/modules/export.js
Displays document count, does not display line numbers in editor, removes editor 80 character gutter line.
- ~New tests and/or benchmarks are included~
- ~Documentation is changed or added~
Currently when opening up the export modal, you don't get to see the current document count with the initial query. It's displayed as `null`. This PR includes a document count on open, and populates that number.
Some folks were confused that the editor in export modal is not editable, so I am removing the lines to hopefully indicate that a bit more.
Also, for aesthetic purposes, removing the gutter line for the editor.
> UX improvements: display doc count, do not display line numbers

- README.md
- src/components/export-select-output/export-select-output.jsx
- src/modules/compass/app-registry.js
- src/modules/compass/global-app-registry.js
- src/modules/export.js
- src/modules/import.js
Add back `globalAppRegistryEmit` now that it has been located. 
#14 pointed out `refresh-data` not being called. b490f6844bba99306f37e85b99fde8465969d82a figured out that this was due to a mixup in the migration to streams for `4.1.0`. The old rx epic encouraged reducers to modify global state so an existential emit on globalAppRegistry would happen for every appRegistry `emit()`. However, in `>=4.1.0` with no rx, the existential is dropped and `globalAppRegistry` was confounding to locate in the ducks scoped state model. There is definitely a better way to do this than what's in b490f6844bba99306f37e85b99fde8465969d82a today. Longer-term, see open questions below.
For the time being, just closing the loop on #14 and getting this shipped :)
Can see in the background the collection has …
> fix(export): Add global app registry emit for import-finished

- .prettierrc
- README.md
- package-lock.json
- package.json
- src/modules/import.js
- src/utils/bson-csv.js
- src/utils/dotnotation.js
- src/utils/dotnotation.spec.js
- src/utils/formatters.js
- src/utils/import-apply-types-and-projection.js
- src/utils/import-apply-types-and-projection.spec.js
Fixes a bug in the import preview where `_bsontype` would be displayed as a property column if you selected an import source that included bson such as an extended `.json`.
- ☑️  Import: Move away from `state.fields` being array of objects to using all array's of strings. For now, there is some duplication of fields+transforms+excludes we'll come back to and fixup.
- ☑️ import-apply-type-and-projection supports nested dotnotation and only uses `state.importData.transforms`
- Makes code much simpler. Leaving `state.importData.fields` for now as still convenient for column headers in `<importPreview />` and may do some more work there in the future
- import-apply-type-and-projection stream returns a noop `PassThrough` if user has not declared any transforms/exclusions
- Should we be calling …
> COMPASS-3997: Fix import preview handling nested documents and bson

- package-lock.json
- package.json
- src/components/import-preview/import-preview.jsx
- src/modules/import.js
- src/utils/bson-csv.js
- src/utils/bson-csv.spec.js
- src/utils/get-shell-js.js
- src/utils/import-preview.js
- chore: Upgrade to javascript-stringify@2 b5bdc7b Fixes #56
- fix(import): Preview table values always strings 29148cd Fixes COMPASS-4164
- fix(import): Hard limit reading fs for preview to first 20kb so preview always shows as fast as possible.
> fix(import): COMPASS-4164 Preview table values always strings

- .travis.yml
- package-lock.json
- package.json
- src/utils/formatters.js
- src/utils/formatters.spec.js
- src/utils/import-preview.spec.js
- src/utils/import-size-guesstimator.spec.js
- src/utils/remove-blanks.spec.js
> chore(import): Add export EJSON formatter tests

- src/modules/export.js
- src/modules/import.js
- src/modules/import.spec.js
- src/utils/bson-csv.js
- src/utils/bson-csv.spec.js
- src/utils/dotnotation.spec.js
- src/utils/formatters.js
- src/utils/formatters.spec.js
- fix(import): COMPASS-4206: Make type detection/casting work right when importing/exporting `.json`. a093933
Importing correctly picks up ObjectID, Number, and Date:
- fix(export): Pick up nested objects to include in projection f6baf06
```javascript
doc = {
_id: 'Arlo', 
location: {
place: 'home',
activity: {
sleeping: true,
is: 'on the couch'
}
};
```
Before this would populate the projection as:
Now you can specify full paths for more control over what is actually returned:
Use case: (See a 1M line csv imported that is 300 fields wide and you only want 2).
- fix(export): Add tests to make sure csv's have correct headers. df70ff9
Headers should be dotnotation for nested object paths.
> fix(import): COMPASS-4206: Fix type detection and export formatting.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- src/components/import-modal/import-modal.jsx
- src/components/import-options/import-options.jsx
- src/components/import-preview/import-preview.spec.js
- src/components/select-field-type/select-field-type.spec.js
- src/modules/import.js
- src/modules/import.spec.js
- src/utils/bson-csv.spec.js
- src/utils/import-preview.js
- src/utils/import-preview.spec.js
- src/utils/import-size-guesstimator.js
- src/utils/import-size-guesstimator.spec.js
- According to the design https://mongodb.invisionapp.com/share/BVNOZB4DYT3#/screens/316135806 and having in mind that json documents can have nested properties that can't be properly presented in the table view we should display import preview only for csv files, and do not display to for json files.
- Add GitHub templates
> COMPASS-4298: Show preview only for csv files

- src/components/error-box/error-box.jsx
- src/components/error-box/error-box.less
- src/modules/import.js
- src/utils/import-apply-types-and-projection.js
- src/utils/import-apply-types-and-projection.spec.js
COMPASS-4352
This PR adds a try catch to our bson type casting in the import pipeline, so when bson type transformations error it doesn't crash compass. Interestingly this only happens on a few kinds of conversions. `String` -> `Decimal128` errors, while `String` -> `Number` does not (It makes `NaN`). This is the current behavior, I don't think we've heard too much on how people feel about it so maybe its not an issue but maybe something we want to address sometime.
Also did a `overflow-wrap: break-word` on the error box to fix COMPASS-4250:
*before*
*after*
> COMPASS-4352: Error handle failing type casting

- package-lock.json
- package.json
- src/utils/formatters.spec.js
Provide a fix for wrong Binary data serialization in the
bson package.
The relevant changes have already been made on the master branch of
the js-bson repository, but not released yet. Since they are part
of larger changes, a one-off release to push them out is not planned.
Therefore we temporarily use a fork of the package here.
> COMPASS-4426 - Work around bson package bugs

- electron/renderer/index.js
- src/components/export-modal/export-modal.jsx
- src/components/export-select-output/export-select-output.jsx
- src/utils/file-save-dialog.js
- src/utils/formatters.spec.js
This PR makes it so the export output file popup filename is pre-filled with the name of the collection being exported. 
https://github.com/mongodb-js/compass/issues/1934
> Prefill export filename

- src/utils/bson-csv.js
- src/utils/bson-csv.spec.js
- src/utils/formatters.js
In the past Compass automatically converted string values that matched `"0", "1", "false", "true", "FALSE", "TRUE", "", "null", "NULL"` to the boolean `true` or `false` during exporting to CSV.
This conversion is now disabled and the values are exported as they are. Only "real" boolean values will be exported as `true` or `false`. This is in line with the behavior of `mongoexport`.
> fix: Do not auto-convert string values to boolean COMPASS-4466

- package-lock.json
- package.json
- src/components/export-select-fields/export-select-fields.jsx
- src/modules/export.js
- src/modules/export.spec.js
Fixes two things:
1. All inserted fields in 'Export' are shown in order they're inserted. That is,
the field currently inserted by the user is listed as last instead of as first.
2. Shows all fields to be exported. This introduces two more things:
- We now sample 100 documents from the current collection to get more
accurate field information.
- Those 100 documents are run through `mongodb-schema` to get all field
paths.
- Do we want to sample more than 100 documents? Should we sample less?
> fix(COMPASS-4449): display all fields in coll to be exported

- package-lock.json
- package.json
- src/utils/get-shell-js.js
- src/utils/get-shell-js.spec.js
This adds a dependency to https://github.com/mongodb-js/query-parser/ to be able to use its `stringify` method that prints a query correctly including BSON types.
> fix: Add mongodb-query-parser and use its stringify COMPASS-4481

- .babelrc
- package-lock.json
- package.json
- src/modules/export.js
- src/modules/load-fields.js
- src/modules/load-fields.spec.js
- test/setup.js
This is a pre-requisite to COMPASS-4154, since that contains a breaking change for import/export.
Rather than adapting this code to the new `dataService.sample` here we just switch back to a plain `find`, since in practice the accuracy is similar but the performance is better compared to a `$sample` aggregation.
> fix: use find to infer fields COMPASS-4154

- src/components/import-options/import-options.jsx
- src/modules/import.js
- src/utils/import-apply-types-and-projection.js
- src/utils/import-apply-types-and-projection.spec.js
The call to `transformProjectedTypesStream()` uses `ignoreBlanks`,
not `removeBlanks`, so pick one and stick with it. This renders
the `Ignore empty strings` checkbox functional again.
For JSON, never ignore empty strings, and don’t display the checkbox.
As a drive-by fix, make the `<label>` elements wrap their corresponding
inputs so that they are associated with them.
> fix: fix “Ignore empty strings” (COMPASS-4458, COMPASS-4594)

- src/components/export-modal/export-modal.jsx
- src/components/export-select-fields/export-select-fields.jsx
- src/modules/export.js
- src/modules/export.spec.js
- src/modules/load-fields.js
- src/modules/load-fields.spec.js
- src/utils/formatters.js
- src/utils/formatters.spec.js
fast-csv autodetects columns based on the first row of data
when we don’t pass in the headers explicitly.
Start passing in the headers explicitly so that all selected
columns are included in the resulting CSV.
> fix: export all fields in CSV COMPASS-4332

- .eslintrc
- electron/renderer/components/import-export/import-export.jsx
- examples/error-box.stories.js
- src/components/error-box/error-box.jsx
- src/components/export-modal/export-modal.jsx
- src/components/import-modal/import-modal.jsx
- src/components/import-modal/import-modal.less
- src/components/import-preview/import-preview.jsx
- src/components/progress-bar/progress-bar.jsx
- src/components/progress-bar/progress-bar.less
- src/components/select-field-type/select-field-type.jsx
- src/constants/process-status.js
- src/modules/import.js
- src/modules/import.spec.js
- src/utils/collection-stream.js
- src/utils/import-parser.js
This PR addresses the original issue specified in COMPASS-4571 but also makes several adjustments to the UI as without them the numbers reported by fixed `collection-stream` were not represented in the UI in a way that makes sense (e.g., you could get a progress bar that is filled only half way through when the UI reports "100% completed" progress, or a green progress bar with error reported, or only one error reported when not a single document was uploaded). Following is a comparison of some states before and after the change:
https://user-images.githubusercontent.com/5036933/111973927-47278d00-8aff-11eb-9402-4474cf66efab.mp4
https://user-images.githubusercontent.com/5036933/111972134-67564c80-8afd-11eb-92b5-adb001a3cc6f.mp4
https://user-images.githubusercontent.com/5036933/111973947-4c8 …
> refactor: Refactor collection stream to report progress better and adjust import UI to represent progress im a more meaningful way COMPASS-4571

- src/utils/collection-stream.js
Instead of returning `(err, undefined)` in the `bulkWrite` callback, driver seems to return `(err, null)` in some rare cases, which breaks `_mergeBulkOpResult` call and fails the import even if `stopOnError` is `false`, this PR handles the corner case by making sure that `_mergeBulkOpResult` will always gets an object
> fix(collection-stream): Handle null result when bulkWrite fails
